apiVersion: v1
kind: Namespace
metadata:
  name: jgedeon007-namespace 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: jgedeon007-namespace
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      
      containers:
      - name: flask
        image: jgedeon007/flaskapp
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: jgedeon007-namespace
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---      